// eslint-disable-next-line

export const fakeFavPalettes = [
    {
        id: 1,
        userId: 1,
        paletteName: '이름1',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 2,
        userId: 15,
        paletteName: '이름2',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 3,
        userId: 5,
        paletteName: '이름3',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 4,
        userId: 78,
        paletteName: '이름4',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 5,
        userId: 1000,
        paletteName: '이름5',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 6,
        userId: 10000,
        paletteName: '이름6',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 7,
        userId: 100000,
        paletteName: '이름7',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 8,
        userId: 1000000,
        paletteName: '이름8',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 9,
        userId: 10101010,
        paletteName: '이름9',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 10,
        userId: 1202020020,
        paletteName: '이름10',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 11,
        userId: 190909900,
        paletteName: '이름11',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 12,
        userId: 17075540,
        paletteName: '이름12',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 13,
        userId: 1,
        paletteName: '이름13',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 14,
        userId: 150508,
        paletteName: '이름14',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 15,
        userId: 1788780,
        paletteName: '이름15',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 16,
        userId: 178076352,
        paletteName: '이름16',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
];

export const fakeCurrentPalettes = [
    {
        id: 1,
        userId: 1,
        paletteName: '이름1',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 2,
        userId: 15,
        paletteName: '이름2',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 3,
        userId: 5,
        paletteName: '이름3',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
    {
        id: 4,
        userId: 78,
        paletteName: '이름4',
        colorCode: [
            '#55efc4',
            '#81ecec',
            '#74b9ff',
            '#a29bfe',
            '#6c5ce7',
            '#0984e3',
            '#00cec9',
        ],
        description: '색갈피설명',
    },
];
