# Generated by Django 3.1.1 on 2020-09-12 16:12

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palettes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('paletteName', models.CharField(max_length=256)),
                ('description', models.TextField(default='')),
                ('colors', django_mysql.models.ListCharField(models.CharField(max_length=7), max_length=77, size=7)),
                ('visit', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
