# Generated by Django 3.1.1 on 2020-09-19 14:33

from django.db import migrations, models
import django_mysql.models
import palettes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('paletteName', models.CharField(max_length=256, validators=[palettes.models.validate_palette_Name])),
                ('description', models.TextField(default='', validators=[palettes.models.validate_palette_Description])),
                ('colors', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=77, size=7)),
                ('visit', models.IntegerField(default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
