<<<<<<< HEAD
# Generated by Django 3.1.1 on 2020-09-11 04:35
=======
# Generated by Django 3.1.1 on 2020-09-12 16:12
>>>>>>> c1a71a7e472f5344396f9077bd1394de3707532f

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palettes',
            fields=[
<<<<<<< HEAD
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=255)),
                ('paletteName', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('colors', django_mysql.models.ListCharField(models.CharField(max_length=7), max_length=77, size=7)),
                ('visit', models.CharField(max_length=255)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('paletteName', models.CharField(max_length=256)),
                ('description', models.TextField(default='')),
                ('colors', django_mysql.models.ListCharField(models.CharField(max_length=7), max_length=77, size=7)),
                ('visit', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
>>>>>>> c1a71a7e472f5344396f9077bd1394de3707532f
            ],
        ),
    ]
